apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example:ipam-controller
rules:
- apiGroups:
  - network.example.com
  resources:
  - subnets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - network.example.com
  resources:
  - networkattachments
  - iplocks
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
